name: Deploy Node.js Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sync Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "/home/userwww/web/empstateweb.com/public_html"
          strip_components: 1
          excludes: |
            .git/**
            .github/**
            node_modules/**

      - name: Final Setup on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 90m
          script: |
            cd /home/userwww/web/empstateweb.com/public_html
            chown -R www-data:www-data /home/userwww/web/empstateweb.com/public_html
            chmod -R 775 /home/userwww/web/empstateweb.com/public_html
            npm install
            pm2 start index.js --name "empstateweb" --watch
            pm2 save
            